[phases.setup]
nixPkgs = ["nodejs", "chromium"]

[phases.build]
cmds = ["npm ci --only=production"]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NIXPACKS_NO_CACHE = "true"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/store/*/bin/chromium"